services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "${CHROMA_PORT}:${CHROMA_PORT}"
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=${CHROMA_PORT}
      - PERSIST_DIRECTORY=${CHROMA_PERSIST_DIR}
      - ANONYMIZED_TELEMETRY=FALSE
    volumes:
      - chroma_data:${CHROMA_PERSIST_DIR}

  api:
    build:
      context: .
      dockerfile: app/src/services/api/Dockerfile
    container_name: rag-api
    ports:
      - "${API_PORT}:8000"
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=${CHROMA_PORT}
      - CHROMA_COLLECTION=${CHROMA_COLLECTION}
    depends_on:
      - chroma
  
  streamlit-dashboard:
    build:
      context: .
      dockerfile: app/src/services/ui/Dockerfile
    container_name: streamlit-dashboard
    ports:
      - "${DASHBOARD_PORT}:8000"
    depends_on:
      - api

volumes:
  chroma_data:
